name: tidepool-data-science-simulator-dev
channels:
  - defaults
  - conda-forge

dependencies:
  - black
  - coverage
  - flake8
  - matplotlib
  - mypy
  - numexpr
  - numpy
  - pandas
  - pip
  - plotly
  - plotly-orca
  - pre-commit
  - pytest
  - python
  - requests
  - scipy
  - seaborn
  
  - pip:
    - backports-datetime-fromisoformat
    - pip-chill
    - python-dotenv
    - filterpy
    - -e ../data-science-models
    - -e ../PyLoopKit
    - -e ../data-science-metrics
    - -e ../LoopAlgorithmToPython