name: tidepool-data-science-simulator
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.12
  - black
  - coverage
  - flake8
  - matplotlib
  - mypy
  - numpy
  - pandas
  - pip
  - plotly
  - plotly-orca
  - pre-commit
  - pytest
  - python-dotenv
  - requests
  - scipy
  - seaborn
  - pip:
    - pydantic>=2.0
    - openpyxl==3.1.5
    - pip-chill==1.0.0
    - python-dotenv==0.13.0
    - -e file:/Users/shawnfoster/PycharmProjects/data-science-models
    - git+https://github.com/tidepool-org/Pyloopkit@dev
    - git+https://github.com/tidepool-org/data-science-metrics
    - -e file:/Users/shawnfoster/PycharmProjects/data-science-simulator-v2/LoopAlgorithmToPython
